### ISSUE TITLE
Too low contrast on reply box of thread view right pannel

### ISSUE THREAD

**Issue by ovidiubuligan** [laCour/slack-night-mode#211] opened 2019-02-25 11:54 UTC
while you are typing a reply in a thread view this is how it is visible:
![image](https://user-images.githubusercontent.com/4757459/53335621-9ee57100-3904-11e9-986a-03bcb8bb43ab.png)

The contrast is too low for the typing text . It should be a bit darker . OR it can made maybe to look like the normal message box which is white text on dark background: 
![image](https://user-images.githubusercontent.com/4757459/53335698-d3f1c380-3904-11e9-96a2-920c22eade82.png)

**Comment by Lemmmy** [comment] 2019-02-25 12:26
Duplicate of #206 and #184

**Closed as completed** 2019-03-04 01:43 UTC
