### ISSUE TITLE
Thread text field is white again

### ISSUE THREAD

**Issue by tzm41** [laCour/slack-night-mode#206] opened 2019-01-24 17:05 UTC
Text input also is white on white, making it hard to see.

<img width="469" alt="screen shot 2019-01-24 at 12 01 49 pm" src="https://user-images.githubusercontent.com/5728283/51695121-4d2d8c00-1fd0-11e9-82e5-2100b4be9c53.png">

**Comment by jon-sully** [comment] 2019-01-24 17:11
Thanks for opening this @tzm41, was about to do the same. Can confirm on the latest Slack update (new logo update 😒)

**Comment by tzm41** [comment] 2019-01-24 18:09
The new logo is kinda meh

**Comment by jon-sully** [comment] 2019-01-28 22:11
I didn't see anything happen in this repo for this issue but it looks fixed now on my environment? Not sure how that happened. @tzm41 do you still see this issue?

**Comment by tzm41** [comment] 2019-01-28 22:35
Seems like it’s fixed.

**Comment by laCour** [comment] 2019-01-29 01:36
Weird. Good to hear though. Let me know if this comes back.

**Comment by pseeth** [comment] 2019-01-31 03:28
This is still broken for me. Using macOS, Slack from App Store, 3.3.7 w/ the latest compiled css. What versions is everyone else using for it to work?

**Comment by tzm41** [comment] 2019-01-31 03:32
It’s broken again. Feels like Slack is switching things around.

**Comment by devkev** [comment] 2019-02-18 03:36
Any chance of a fix for this?  It's been a while now, and it's depressing getting blinded (because I have to disable the userstyle) every time I need to reply to a thread...

**Comment by oliverseal** [comment] 2019-02-19 16:33
I mmmmight fork and put up a pull request for this later when I'm not at work. In the meantime, add the following to your ssb-interop.js right under the line that starts with `let tt_customCss ...`

```javascript
tt__customCss += '.p-threads_footer__input .p-message_input_field {background: #545454; border-color: #363636; color: #e6e6e6;}\n' +
'.p-threads_footer__input .p-message_input_file_button:not(:hover) { border-color: #363636; }\n' +
'.p-threads_footer__input .p-message_input_file_button { background-color: #363636 !important; }\n';
```

**Comment by benjaminkay93** [comment] 2019-02-19 20:14
@oliverseal I can't seem to find a `tt_customCss` variable in the `ssb-interop.js`

**Comment by oliverseal** [comment] 2019-02-19 20:24
That's fair. Here's the full event listener I have at the bottom of mine for a more full reference:
```javascript
//...
document.addEventListener('DOMContentLoaded', function() {
    let tt__customCss = '.menu ul li a:not(.inline_menu_link) {color: #fff !important;}\n';
    tt__customCss += '.p-threads_footer__input .p-message_input_field {background: #545454; border-color: #363636; color: #e6e6e6;}\n' +
    '.p-threads_footer__input .p-message_input_file_button:not(:hover) { border-color: #363636; }\n' +
    '.p-threads_footer__input .p-message_input_file_button { background-color: #363636 !important; }\n'
    $.ajax({
         url: 'https://cdn.rawgit.com/laCour/slack-night-mode/master/css/raw/black.css',
        success: function(css) {
            $('<style></style>').appendTo('head').html(css + tt__customCss);
        }
   });
});
```

**Comment by zkrige** [comment] 2019-02-20 11:18
I'm using https://github.com/mykeels/slack-theme-cli and this issue is still happening
is there an easy fix for this?

**Comment by calebboyd** [comment] 2019-02-21 15:51
@zkrige I added support for this in the [dark-slack cli](https://github.com/calebboyd/dark-slack)

Put the custom css in a file run it with `dark-slack --add-css ./custom.css` Should work for most while waiting for official theme patches!

**Comment by shadedurza** [comment] 2019-02-21 17:34
Confirmed that replacing what I had in ssb-interop.js with what @oliverseal posted above works for me.
![image](https://user-images.githubusercontent.com/39968280/53189329-dedaea00-35cc-11e9-8fe6-6eb50f1a8913.png)

**Comment by zkrige** [comment] 2019-02-22 05:30
@calebboyd thank you so much!

**Comment by Linesmerrill** [comment] 2019-03-01 20:12
@oliverseal Thank you! Good fix until this is updated. 👍

**Closed as completed** 2019-03-04 01:43 UTC

**Comment by Colin-Tan-Intrepid** [comment] 2019-03-05 22:48
This shouldn't be closed just yet as `https://cdn.rawgit.com/laCour/slack-night-mode/master/css/raw/black.css` file has not been updated.
