### ISSUE TITLE
Background colour of chat window is white

### ISSUE THREAD

**Issue by djhworld** [laCour/slack-night-mode#158] opened 2018-04-17 07:49 UTC
Slack must have made a change overnight, the background colour of the chat window has changed to white.

**Comment by lkonga** [comment] 2018-04-17 07:53
I am experiencing the same.

**Comment by jlanza** [comment] 2018-04-17 08:17
Is it so difficult for slack to implement a dark theme? It is a electron (like web) site, so a CSS can make it.

**Comment by ChipWolf** [comment] 2018-04-17 08:30
@jlanza this project is CSS.... 4000 lines of it https://github.com/laCour/slack-night-mode/blob/master/css/black.css
That's how Stylish themes work

**Comment by jlanza** [comment] 2018-04-17 08:55
I know, but at the end it is not official. This is what I meant. They should provide something official.

**Comment by sandfox** [comment] 2018-04-17 09:08
FYI it looks like #157 fixes this issue! 

using https://raw.githubusercontent.com/tectiv3/slack-night-mode/master/css/raw/black.css as the CSS url to test it

**Comment by odedelharar** [comment] 2018-04-17 10:10
See https://github.com/widget-/slack-black-theme/issues/48

**Comment by bklaas** [comment] 2018-04-17 14:49
I can confirm sandfox's comment above is a fix for both 2.8.2 and 3.1 Slack desktop clients for Linux. The latter, dark mode in 3.1, had been broken for months, while 2.8.2 just broke this morning. Both work now with that updated css URL. Woot!

**Comment by laCour** [comment] 2018-04-17 15:39
I've merged in #159 which resolves this, and have cut a new release. Let me know if you still encounter issues.

**Closed as completed by laCour** 2018-04-17 15:39 UTC

**Comment by cbenard** [comment] 2018-04-17 15:42
This isn't fixed. @sandfox's link works from @tectiv3. This is in the desktop app adding the CSS to `ssb-interop.js`

```document.addEventListener('DOMContentLoaded', function() {
 $.ajax({
   // Broken (white bg)
   //url: 'https://cdn.rawgit.com/laCour/slack-night-mode/master/css/raw/black.css',
   // Working
   url: 'https://cdn.rawgit.com/tectiv3/slack-night-mode/master/css/raw/black.css',
   success: function(css) {
     $("<style></style>").appendTo('head').html(css);
   }
 });
});
```

**Comment by laCour** [comment] 2018-04-17 15:54
@cbenard Do not use rawgit. Try https://raw.githubusercontent.com/laCour/slack-night-mode/master/css/raw/black.css instead.

**Comment by cbenard** [comment] 2018-04-17 15:57
That worked, but the rawgit one is in a prominent example that I presume far more than just me are using (see @sandfox's comment also using rawgit).

What are the differences between the hosts? Caching?

You may want to maintain a canonical set of code to inject in `ssb-interop.js` rather than linking to that old issue comment (if you care about the desktop app).

Thanks for the fix!

**Edit:** I did some reading. `githubusercontent.com` is owned by GitHub and serves everything as text/plain. RawGit is a caching proxy not run by GitHub at all but by a third party and serves the appropriate mimetypes. In the case of this CSS, I guess `text/plain` doesn't matter. Good to know.
